---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
  namespace: default
  labels:
    test.longhorn.io: e2e
spec:
  selector:
    matchLabels:
      app: test-statefulset
  serviceName: test-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: ubuntu
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        name: sleep
        command: ['/bin/sh', '-c']
        args: ['while true;do date;sleep 5; done']
        volumeMounts: []
        volumeDevices:
        - name: pod-data
          devicePath: /dev/longhorn/longhorn-test-blk
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
  - metadata:
      name: pod-data
      labels:
        test.longhorn.io: e2e
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 3221225472  #3Gi
